<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Product>Enzan</Product>
    <Authors>ycanardeau</Authors>
    <PackageProjectUrl>https://github.com/ycanardeau/Enzan</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ycanardeau/Enzan</RepositoryUrl>
    <Description>Enzan is an x86 emulator written in C#.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>Aigamo.Enzan.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>Aigamo.Enzan.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aigamo.Extensions.Primitives\Aigamo.Extensions.Primitives\Aigamo.Extensions.Primitives.csproj" />
  </ItemGroup>

</Project>
