using System.Collections.Immutable;
using Aigamo.Otsuki.Messages.Core;

namespace Aigamo.Otsuki;

/// <summary>
/// Describes a game session, like DPN_APPLICATION_DESC.
/// </summary>
public sealed record ApplicationDescription
{
	/// <summary>
	/// Identifies the game. Peers can only join sessions of the same application.
	/// </summary>
	public Guid GuidApplication { get; init; }

	/// <summary>
	/// Identifies the session. Generated by the host when empty; a joining peer can leave it empty.
	/// </summary>
	public Guid GuidInstance { get; init; }

	public SessionFlags Flags { get; init; } = SessionFlags.NoDpnServer;

	/// <summary>
	/// Maximum number of players including the host, or 0 for no limit.
	/// </summary>
	public int MaxPlayers { get; init; }

	public string SessionName { get; init; } = string.Empty;

	/// <summary>
	/// Required to join when <see cref="SessionFlags.RequirePassword"/> is set.
	/// </summary>
	public string Password { get; init; } = string.Empty;

	public ImmutableArray<byte> ApplicationReservedData { get; init; } = [];
}
